services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  db:
    image: alpine
    build: ./database
    volumes:
      - db_data:/var/lib/sqlite3

volumes:
  db_data:
