version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    networks:
      - app-network
    ports:
      - "8000:8000"  # Porta do backend
    depends_on:
      - db

  frontend:
    build: ./frontend
    networks:
      - app-network
    ports:
      - "80:80"  # Porta do frontend
    depends_on:
      - backend

  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
