version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/books.json:/app/books.json
    networks:
      - app-network
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
