services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/books.json:/app/books.json  # Mapeamento do arquivo JSON para o container
    ports:
      - "5000:5000"
