services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=sqlite:///./database.db
    depends_on:
      - database

  database:
    build: ./database
    volumes:
      - ./database:/data
